package com.mustly.wellmedia.lib.annotation

/**
 *
 *
 * Created by Cheney on 2017/1/12.
 */
object Constants {
    const val OPTION_MODULE_NAME = "moduleName"
    const val DEFAULT_MODULE_NAME = "Default"

    const val META_VALUE = "com.mustly.wellmedia.lib.commonlib.route.moduleName"

    const val CLASS_DOC = "Generated by Route annotation Processor. Do not edit it!"

    const val ACTIVITY_FULL_NAME = "android.app.Activity"
    const val FRAGMENT_FULL_NAME = "android.app.Fragment"
    const val FRAGMENT_X_FULL_NAME = "androidx.fragment.app.Fragment"

    const val GENERATED_ROUTE_REGISTER_PATH = "com.mustly.wellmedia.lib.commonlib.route.generated"

    const val METHOD_REGISTER = "register"

    const val ROUTE_REGISTER = "RouteRegister"
    const val ROUTE_REGISTER_INTERFACE_NAME = "com.mustly.wellmedia.lib.commonlib.route.$ROUTE_REGISTER"
}